### ISSUE TITLE
Integration with TravisCI

### ISSUE THREAD

**Issue by jasonrogena** [ilri/azizi-odk-sensors#1]
I've added support for TravsCI. Someone with Admin rights to toggle monitoring in travis-ci.org

**Comment by alanorth** [comment]
Enabled builds for this repo on travis-ci.org... the status icon in the readme should update soon.

**Comment by alanorth** [comment]
Ok, I had to push a bs commit to trigger the first build... which failed. Log here: https://gist.github.com/alanorth/782973e9f86e41260275
